name: yawkat-t2
main: com.tenjava.entries.yawkat.t2.TenJava
version: '${project.version}'
permissions:
    energy.display.self:
        description: Allows displaying own energy level.
        default: true
    energy.add:
        description: Allows adding energy to players.
        default: op
    energy.action.strike:
        description: Allows using the /strike command to cast a lightning strike.
        default: true
commands:
    energy:
        description: Display your current energy level.
        usage: /<command>
        permission: energy.display.self
    energyadd:
        description: Display your current energy level.
        usage: /<command> <player> <amount>
        permission: energy.add
    strike:
        description: Cast a lightning strike at the block you're looking at, costing 20 energy.
        usage: /<command>
        permission: energy.action.strike