name: yawkat-t2
main: com.tenjava.entries.yawkat.t2.TenJava
version: '${project.version}'
permissions:
    energy.display.self:
        description: Allows displaying own energy level.
        default: true
    energy.add:
        description: Allows adding energy to players.
        default: op
commands:
    energy:
        description: Display your current energy level.
        usage: /<command>
        permission: energy.display.self
    energyadd:
        description: Display your current energy level.
        usage: /<command> <player> <amount>
        permission: energy.add