name: yawkat-t2
main: com.tenjava.entries.yawkat.t2.TenJava
version: '${project.version}'
permissions:
    energy.display.self:
        description: Allows displaying own energy level.
        default: true
    energy.add:
        description: Allows adding energy to players.
        default: op
    energy.remove:
        description: Allows removing energy from players.
        default: op
    energy.action.strike:
        description: Allows using the /strike command to cast a lightning strike.
        default: true
    energy.action.discharge:
        description: Allows using the /discharge command to discharge energy and damage enemies.
        default: true
commands:
    energy:
        description: Display your current energy level.
        usage: /<command>
        permission: energy.display.self
    energyadd:
        description: Add energy to a player.
        usage: /<command> <player> <amount>
        permission: energy.add
    energyremove:
        description: Remove energy from a player.
        usage: /<command> <player> <amount>
        permission: energy.remove
    strike:
        description: Cast a lightning strike at the block you're looking at, costing 20 energy.
        usage: /<command>
        permission: energy.action.strike
    discharge:
        description: Discharge either a specified amount of energy or your remaining energy. Damages and blinds nearby entities.
        usage: /<command> [energy amount]
        permission: energy.action.discharge
    charge:
        description: Charge a furnace with energy.
        usage: /<command> <energy amount>
        permission: energy.action.discharge